### ISSUE TITLE
JMS Consumer for adding comments.

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/BlogRest#12]
## Estimated time spent 10 hours.
* Add the ability to listen queue in activeMQ server.
* The data is sent in json format, so needed to map the comment objects using Jackson.
* Comments are added synchronously so you need to send a response.

**Comment by aleksieiev** [comment]
> Add the ability to listen queue in activeMQ server.

Who should be able to to listen?

**Comment by evtushenko-sasha** [comment]
The backend must have several mechanisms by which it must listen to the activeMQ queue.

**Comment by evtushenko-sasha** [comment]
Implemented in this [commit](https://github.com/JavaBraveWarriors/BlogRest/tree/d241d3202f4aff8b1a734d6234791c82ab68d141).
