### ISSUE TITLE
Comparison of types of pull connections for DB.

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/BlogRest#14]
### In Spring docs indicated this DataSource: 
1) Apache Commons DBCP2:
* Easy to configure. Very detailed configuration page.
* Supports prepared statement caching
* Does not validate connections on borrow
* Does not reset transaction isolation when returns to the pool
* Does not reset read-only status of the connection
* Does not reset auto-commit status of the connection
* Does not clear SQL warnings
* Does not validate connections on borrow
2) C3P0:
* C3P0 is one of the oldest and best-known libraries. It is very well documented. However, according to some reports, it’s easy to misconfigure the pool and can result in poor performance and deadlocks.
* Comes in package with hibernate.
* Works well in the heavy concurrent environment.
* Supports prepared statement pooling
* Resets auto-commit status when returning to the pool
* Resets read the only status when returning to the pool
3) Tomcat JDBC:
* Supports highly concurrent environments and multi-core/CPU systems.
* It is very well documented here.
* Async connection retrieval. Can queue connection requests and return Future back.
* Ability to configure custom interceptors to enhance functionality.
* Provides multiple ways to configure pool. One is inside the Apache container, JMX and standalone by using DataSource bean.
* Does not by default reset auto-commit and transaction levels for connections in the pool, users must configure custom interceptors to do this.
* Does not by default test connections on getConnection()
* Does not close abandoned open statements.
* Pool prepared statement properties are not used.
4) HikariCP:
* Very light library, around 130 kb.
* Tests connections at getConnection()
* Tracks and closes abandoned connections.
* Clears connections before returning connection to the client.
* Resets auto-commit, transaction isolation, read-only status
* The library has 58 active contributors and has very detailed configuration page with performance benchmarks.
### Performance test:
1.
![Screenshot from 2019-03-19 21-48-02](https://user-images.githubusercontent.com/32134385/54633188-b988b100-4a90-11e9-9197-4b371bb0ad06.png)
![Screenshot from 2019-03-19 21-48-08](https://user-images.githubusercontent.com/32134385/54633197-bab9de00-4a90-11e9-868d-2115436cf4e2.png)
2. We found a [repository](https://github.com/brettwooldridge/HikariCP-benchmark) where all database pool connections are compared
![Screenshot from 2019-03-20 12-04-00](https://user-images.githubusercontent.com/32134385/54683736-7c213380-4b23-11e9-825c-737dc4c59d79.png)
We made a decision to use HikariCP because this connector is the easiest and showed the highest results of this benchmark.

**Comment by aleksieiev** [comment]
Quite good. I propose to add performance test requests and business area for that situation when someone wants to play them back. Next one improvements for understanding of details is connection pool configurations: how many connections has been configured, any additional session cleanup operations, etc. Last but not least is result detalization. Tables contain some time results. Is it average time or time for all 1000 cycles?
And where is conclusion? What's your choice and why?

**Comment by evtushenko-sasha** [comment]
This is time for all 1000 cycles of tests in milliseconds.
Updated.

**Comment by evtushenko-sasha** [comment]
Implemented in this [commit](https://github.com/JavaBraveWarriors/BlogRest/tree/f71d738e514bafde2a711e8600b4295828246784).
