### ISSUE TITLE
Spike: Reserach possible time and date formats fot REST API

### ISSUE THREAD

**Issue by aleksieiev** [JavaBraveWarriors/BlogRest#4]
1. Find the most common used date and time formats suitable for REST API
2. Estimate proc and cons each of variants.
3. Discuss it in this thread and find suitable approach.

**Comment by evtushenko-sasha** [comment]
#### 1) Format ISO-8601
#### pros :
* Regional neutrality
* Time zone offset
minuses: none
#### 2) Timestamp
#### pros:
* Regional neutrality
#### minuses:
* Limited from 1970 to 2038

**Comment by aleksieiev** [comment]
What about time estimations for code changes?

**Comment by evtushenko-sasha** [comment]
The changes will be minimal, since this is due only to the data format, and therefore the time for change is minimal

**Comment by aleksieiev** [comment]
As far as I know First World War also has been planned with **minimal** changes in World politic situation, but all of us knows how long it was.
I added task in Grow how estimate tasks correctly because **minimal** doesn't have any information when users can switch their internal API to the new one.

**Comment by evtushenko-sasha** [comment]
I allocated 2 hours for the implementation of this functionality.
