### ISSUE TITLE
Application deployment process

### ISSUE THREAD

**Issue by aleksieiev** [JavaBraveWarriors/BlogRest#5]
Add required plugins and parameters for deployment on application server (e.g. Tomcat)
Acceptance criteria: 
1. deploy should be done via something very easy way like
`mvn deploy`
2. Update documentation for this process

**Comment by evtushenko-sasha** [comment]
1) The ability to do deploy is added and documented, the description is in the README file.
2) Added documentation how to set up a real environment.

**Comment by evtushenko-sasha** [comment]
In this commit was added opportunity to deploy on tomcat [see](https://github.com/JavaBraveWarriors/BlogRest/tree/bdb0691b12406bb93159abc2ebb4f14a2586406c).
