### ISSUE TITLE
Refactor date and time format in application

### ISSUE THREAD

**Issue by aleksieiev** [JavaBraveWarriors/BlogRest#6]
1. According to [spike](https://github.com/JavaBraveWarriors/BlogRest/issues/4) researches refactor current solution to the new one. 
2. Update both documentation and tests.

**Comment by evtushenko-sasha** [comment]
Implemented in [this](https://github.com/JavaBraveWarriors/BlogRest/tree/63c2438626078ba9ce44dcaf22e49f5605211c03) commit.
